# --------- Namespace ---------
# 元件版本號
apiVersion: v1
# 元件屬性( Pod, Node, Service, Namespace, ReplicationController )
kind: Namespace
metadata:
  # Namespace 名稱
  name: demo-app

---
# --------- db-deploy ---------
# 元件版本號
apiVersion: apps/v1
# 元件屬性( Pod, Node, Service, Namespace, ReplicationController )
kind: Deployment
metadata:
  namespace: demo-app
  # Deployment 名稱
  name: db-deploy
spec:
  # 指定建立多少數量的 Pod
  replicas: 1
  # 定義 Pod 內容
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql-container
          image: bonju0102/k8s-mysql:latest
          # # 強制使用本地 image
          # imagePullPolicy: Never
          ports:
            - containerPort: 3306
              name: db-port
              protocol: TCP
  # 指定這個 Deployment 規則要適用到哪些 Pod
  selector:
    matchLabels:
      app: mysql

---
# --------- db-service ---------
# 元件版本號
apiVersion: v1
# 元件屬性( Pod, Node, Service, Namespace, ReplicationController )
kind: Service
metadata:
  namespace: demo-app
  # Service 名稱
  name: db-svc
spec:
  selector:
    app: mysql
  type: NodePort
  ports:
    - name: db-port
      protocol: TCP
      # ClusterIP port
      port: 3306
      # 容器 port
      targetPort: db-port

---
# --------- Secret ---------
# 元件版本號
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJib25qdTAxMDIiLCJwYXNzd29yZCI6InEwOTg4MTUxODA1IiwiZW1haWwiOiJib25qdS5odWFuZ0BnbWFpbC5jb20iLCJhdXRoIjoiWW05dWFuVXdNVEF5T25Fd09UZzRNVFV4T0RBMSJ9fX0=
# 元件屬性( Pod, Node, Service, Namespace, ReplicationController )
kind: Secret
metadata:
  creationTimestamp: "2022-03-08T13:14:54Z"
  name: docker-sec
  namespace: demo-app
  resourceVersion: "7627"
  uid: b11d5b54-877b-49d3-b06f-91e49bd8685a
type: kubernetes.io/dockerconfigjson
